config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    get "users/:id/edit" => "users/registrations#edit", as: :edit_other_user_registration
    match "users/:id", to: "users/registrations#update", via: [:patch, :put], as: :other_user_registration
    delete "users/:id/destroy", to: "users/registrations#destroy", as: :destroy_other_user_registration
  end

  # schedulesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_groupsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_group_relationsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # general_messagesに関するrouteはメッセージ読み込みアクションを除いて、JSフォーマット以外受け付けない(例外)
  # entriesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # room_messagesに関するrouteは全てJSフォーマット以外受け付けない(例外)

  root "homes#home"

  get "attendances" => "attendances#index"
  get "attendances/search" => "attendances#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "attendances/csv_download" => "attendances#csv_download", constraints: lambda { |req| req.format == :csv }

  get "user/modal_search" => "users#modal_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/search" => "users#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/sidebar_search" => "users#sidebar_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "users/modal_show/:id" => "users#modal_show", as: "user_modal_show", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "general_messages/other_user_chat_ajax" => "general_messages#message_ajax", constraints: lambda { |req| req.xhr? }
  get "general_messages/home_chat_ajax" => "general_messages#home_message_ajax", constraints: lambda { |req| req.xhr? }

  get "schedules/meeting_new" => "schedules#meeting_new", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/add_timer" => "schedules#add_timer", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/date_change" => "schedules#date_change", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "meeting_rooms/join/:id" => "meeting_rooms#join", as: "meeting_rooms_join", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "meeting_rooms/past_index" => "meeting_rooms#past_index"

  post "general_messages/multiple_create" => "general_messages#multiple_create", constraints: lambda { |req| req.xhr? && req.format == :js }

  resources :attendances, only: [:create, :update], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_group_relations, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_groups, only: [:create, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :departments, only: [:new, :create, :edit, :update, :destroy]
  resources :entries, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :general_messages, only: [:show, :create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :schedules, only: [:new, :create, :edit, :update, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :meeting_rooms, only: [:new, :create, :show, :index, :destroy]
  resources :room_messages, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :users, only: [:show, :index]
  resources :paid_holidays, only: [:create, :new]
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord
  attr_accessor :meeting_date, :date
  attr_accessor :room_entry_users

  # public_uid設定
  generate_public_uid

  def to_params
    public_uid
  end

  # MeetingRoomモデル　バリデーション
  validates :name, presence: true, length: { maximum: 15 }
  validates :comment, length: { maximum: 400 }
  validates :start_at, presence: true
  validates :finish_at, presence: true
  validates :meeting_date, presence: true
  validates :room_entry_users, presence: true
  validate :meeting_start_end_check,
           :meeting_date_check,
           :start_finish_date_check

  # Entry関連アソシエーション
  has_many :entries, dependent: :delete_all
  has_many :users, through: :entries

  # RoomMessage関連アソシエーション
  has_many :room_messages, dependent: :delete_all

  # バリデーション　カスタムメソッド
  private

  # 開始時刻が終了時刻より遅いかチェック
  def meeting_start_end_check
    if finish_at.present? && start_at.present? && start_at > finish_at
      errors.add(:finish_at, "開始時刻より終了時刻が早いです")
    elsif finish_at.present? && start_at.present? && start_at == finish_at
      errors.add(:finish_at, "開始時刻と終了時刻が同じです")
    end
  end

  # 開始時刻と終了時刻の日付が違うかチェック
  def start_finish_date_check
    if finish_at.present? && start_at.present? && finish_at.day != start_at.day
      errors.add(:finish_at, "不正な値です")
    end
  end

  # 開始時刻と終了時間の日付が今日より前かチェック
  def meeting_date_check
    if meeting_date.present? && meeting_date < Date.today
      errors.add(:meeting_date, "date_invalid")
    end
  end
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController

  # ログインユーザー以外のアクセス拒否
  before_action :authenticate_user!

  # 自分がエントリーしているルーム以外からのアクセス拒否
  before_action :validation_meeting_room_path, only: [:join]

  # 勤怠情報取得
  before_action :get_sidebar_attendance, only: [:show, :index, :past_index, :new]

  # ルーム一覧と過去ルーム一覧以外からのアクセス拒否
  before_action :validation_rooms_path, only: [:destroy]

  def show
    # 対象ルーム取得
    @meeting_room = current_user.meeting_rooms.find_by(public_uid: params[:id])
    if @meeting_room
      # タイマーON
      @timer_on = true
      # お知らせOFF
      @notice_message = true
      # ルームユーザー取得
      @room_users = @meeting_room.users
      # 全ユーザー取得
      @users = User.all
      # ルームメッセージ取得
      @room_messages = @meeting_room.room_messages.includes(:user)
      @new_message = current_user.room_messages.build
      # 新規外部メッセージ
      @new_general_message = current_user.general_messages.build
      # 部署取得
      @departments = Department.where.not(name: "未設定").includes(:users)
      # コンタクトグループ取得
      @contact_groups = current_user.contact_groups.includes(:users)
    else
      redirect_to meeting_rooms_path
    end
  end

  def join # format :js && ajax only
    # 対象ルーム取得
    @meeting_room = current_user.meeting_rooms.find_by(public_uid: params[:id])
    respond_to do |format|
      if @meeting_room
        format.js
      else
        format.any { redirect_to root_path }
      end
    end
  end

  def index
    # 自分の会議前、会議中ルーム取得
    @entry_rooms = current_user.meeting_rooms
    if params[:name].present? && params[:date].present?
      search_date = Date.parse(params[:date])
      @after_entry_rooms = @entry_rooms.where(
        "finish_at > ? AND name = ? AND start_at > ? AND start_at < ?",
        DateTime.now,
        params[:name],
        search_date.beginning_of_day,
        search_date.end_of_day
      ).order(start_at: "ASC").includes(:users)
    elsif params[:name].present?
      @after_entry_rooms = @entry_rooms.where(
        "finish_at > ? AND name = ?",
        DateTime.now,
        params[:name]
      ).order(start_at: "ASC").includes(:users)
    elsif params[:date].present?
      search_date = Date.parse(params[:date])
      @after_entry_rooms = @entry_rooms.where(
        "finish_at > ? AND start_at > ? AND start_at < ?",
        DateTime.now,
        search_date.beginning_of_day,
        search_date.end_of_day
      ).order(start_at: "ASC").includes(:users)
    else
      @after_entry_rooms = @entry_rooms.where(
        "finish_at > ?", DateTime.now
      ).order(start_at: "ASC").includes(:users)
    end
  end

  def past_index
    # 自分の過去のルーム取得
    @entry_rooms = current_user.meeting_rooms
    if params[:name].present? && params[:date].present?
      search_date = Date.parse(params[:date])
      @past_rooms = @entry_rooms.where(
        "finish_at < ? AND name = ? AND start_at > ? AND start_at < ?",
        DateTime.now,
        params[:name],
        search_date.beginning_of_day,
        search_date.end_of_day
      ).order(start_at: "DESC").includes(:users)
    elsif params[:name].present?
      @past_rooms = @entry_rooms.where(
        "finish_at < ? AND name = ?",
        DateTime.now,
        params[:name]
      ).order(start_at: "DESC").includes(:users)
    elsif params[:date].present?
      search_date = Date.parse(params[:date])
      @past_rooms = @entry_rooms.where(
        "finish_at < ? AND start_at > ? AND start_at < ?",
        DateTime.now,
        search_date.beginning_of_day,
        search_date.end_of_day
      ).order(start_at: "DESC").includes(:users)
    else
      @past_rooms = @entry_rooms.where(
        "finish_at < ?", DateTime.now
      ).order(start_at: "DESC").includes(:users)
    end
  end

  # ミーティングルーム新規作成フォーム
  def new
    # 新規ミーティングルーム
    @meeting_room = MeetingRoom.new
    # 全ユーザー取得
    @users = User.all
    # 部署取得
    @departments = Department.where.not(name: "未設定").includes(:users)
    # コンタクトグループ取得
    @contact_groups = current_user.contact_groups.includes(:users)
  end

  # ミーティングルーム新規作成
  def create
    # ルーム日付変換
    room_date = params[:meeting_room][:meeting_date]
    room_date = Date.parse(room_date) if room_date.present?
    # エントリーさせるユーザーを取得
    add_users_id = params[:meeting_room][:room_entry_users]
    entry_users = User.where(
      public_uid: add_users_id
    ).where.not(
      public_uid: current_user.public_uid
    )
    # ミーティングルーム作成
    @meeting_room = MeetingRoom.new(
      name: params[:meeting_room][:name],
      comment: params[:meeting_room][:comment],
      start_at: meeting_start_time,
      finish_at: meeting_end_time,
      meeting_date: room_date,
      room_entry_users: entry_users,
    )
    if @meeting_room.save
      begin
        # ルームにユーザーを追加
        @meeting_room.users << entry_users
        @meeting_room.users << current_user
        # ルーム招待メッセージ時間テキスト用
        start_time = @meeting_room.start_at.strftime("%H:%M")
        end_time = @meeting_room.finish_at.strftime("%H:%M")
        # ルームのコメントによる分岐、招待メッセージ作成
        if @meeting_room.comment.present?
          @general_message = current_user.general_messages.create(
            content: "ミーティングルームを予約しました。
                      議題: #{@meeting_room.name}
                      日付: #{@meeting_room.start_at.strftime("%m月%d日")}
                      時間: #{start_time} ~ #{end_time}
                      コメント:
                      #{@meeting_room.comment}",
            room_id: @meeting_room.public_uid,
          )
        else
          @general_message = current_user.general_messages.create(
            content: "ミーティングルームを予約しました。
                      議題: #{@meeting_room.name}
                      日付: #{@meeting_room.start_at.strftime("%m月%d日")}
                      時間: #{start_time} ~ #{end_time}",
            room_id: @meeting_room.public_uid,
          )
        end
        # 招待メッセージの送信先にエントリーさせるユーザーを追加
        if @general_message.present?
          @general_message.receive_users << entry_users
        end
        # ミーティングルーム一覧へリダイレクト
        redirect_to meeting_rooms_path
      rescue
        create_render
      end
    else
      create_render
    end
  end

  # ミーティングルーム削除
  def destroy
    # 対象ルーム削除
    room = current_user.meeting_rooms.find_by(public_uid: params[:id])
    if room
      room.destroy
    end
    redirect_to request.referer
  end

  private

  # ルーム新規作成、開始時間変換
  def meeting_start_time
    hours = params[:meeting_room]["start_at(4i)"]
    minutes = params[:meeting_room]["start_at(5i)"]
    if hours_check(hours) && minutes_check(minutes)
      start = hours + ":" + minutes
      start_tm = params[:meeting_room][:meeting_date] + " " + start
      return start_tm
    else
      return false
    end
  end

  # ルーム新規作成、終了時間変換
  def meeting_end_time
    hours = params[:meeting_room]["finish_at(4i)"]
    minutes = params[:meeting_room]["finish_at(5i)"]
    if hours_check(hours) && minutes_check(minutes)
      finish = hours + ":" + minutes
      end_tm = params[:meeting_room][:meeting_date] + " " + finish
      return end_tm
    else
      return false
    end
  end

  # ルーム新規作成時レンダリング
  def create_render
    @users = User.all
    @departments = Department.where.not(name: "未設定").includes(:users)
    @contact_groups = current_user.contact_groups.includes(:users)
    render "new"
  end

  # ルーム一覧と過去ルーム一覧以外からのアクセス拒否
  def validation_rooms_path
    unless request.referer == meeting_rooms_url || request.referer == meeting_rooms_past_index_url
      redirect_to root_path
    end
  end
end

app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper

  #スケジュールパラメータチェック
  def hours_check(hours)
    times = (0..24).to_a
    times.map! { |n| n.to_s }
    times.map! do |n|
      next n if n.length == 2
      "0" + n
    end
    times.include?(hours)
  end

  def minutes_check(minutes)
    times = (0..5).to_a
    times.map! { |n| n.to_s }
    times.map! { |n| n + "0" }
    times.include?(minutes)
  end
end

app/views/meeting_rooms/_device_change_form.html.erb
<span><i class="fas fa-video"></i> ビデオ</span>
<select id="video-change">
  <option value="">変更先の映像を選択してください</option>
  <option value="display">画面をキャプチャする</option>
</select>
<span><i class="fas fa-microphone"></i> マイク</span>
<select id="audio-change">
  <option value="">変更先のマイクを選択してください</option>
</select>
<button id = "device-change-btn">変更</button>

app/views/meeting_rooms/_room_setting.html.erb
<div id = "room-menu">
  <div id = setting-my-video-content>
    <video id = "my-video"></video>
    <span id = "preview-span">プレビュー</span>
  </div>
  <div id = "menu-container">
    <select id="video-select" class = "device-select">
      <option value="">映像を選択してください</option>
      <option value="display">画面をキャプチャする</option>
    </select>
    <select id="audio-select" class = "device-select">
      <option value="">マイクを選択してください</option>
    </select>
    <%= link_to "参加",  meeting_rooms_join_path(@meeting_room.public_uid), id: "room-join-btn", class: "menu-btn", remote: true %>
  </div>
</div>

app/views/meeting_rooms/_room_show.html.erb
<div id = "room-container">
  <div id = "my-video-content">
    <span class = "video-user-name"><%= current_user.name %></span>
  </div>
</div>

app/views/meeting_rooms/index.html.erb
<div id = "common-container">
  <div id = "rooms-menu">
    <span id = "rooms-link" style = "border-bottom: 5px solid #2196f3;">ルーム一覧</span>
    <%= link_to "過去ルーム一覧", meeting_rooms_past_index_path, id: "past-rooms-link" %>
    <%= link_to "新規作成", new_meeting_room_path, id: "new-room-link" %>
    <div id = "menu-search-box">
      <%= form_with url: meeting_rooms_path, local: true, method: :get do |f| %>
        <%= f.label :name, "内容検索" %>
        <%= f.text_field :name %>

        <%= f.label :date, "日付検索" %>
        <%= f.date_field :date %>

        <%= f.submit "検索", id: "button" %>
      <% end %>
    </div>
  </div>
  <div id = "rooms-container">
    <% if @after_entry_rooms.present? %>
      <ul>
        <% room_date = "foo" %>
        <% @after_entry_rooms.each do |room| %>
          <% if room_date != room.start_at.strftime("%m月%d日") %>
            <% room_date = room.start_at.strftime("%m月%d日") %>
            <li class = "room-date-head"><%= room_date %></li>
          <% end %>
          <li class = "room-content">
            <% if room.start_at <= DateTime.now && room.finish_at >= DateTime.now %>
              <span class = "room-status" style = "background: blue;">会議中</span>
            <% elsif room.start_at > DateTime.now %>
              <span class = "room-status" style = "background: green;">待機中</span>
            <% end %>
            <span class = "room-time"><%= room.start_at.strftime("%m月%d日") %> <%= "#{room.start_at.strftime("%H:%M")}~#{room.finish_at.strftime("%H:%M")}" %></span>
            <%= link_to "ルームへ", meeting_room_path(room.public_uid), data: {"turbolinks"=>false}, class: "room-link" %>
            <%= link_to "ルーム削除", meeting_room_path(room.public_uid), class: "room-delete-link", method: :delete, data: { confirm: "ルーム名: #{room.name}を削除しますか？" } %>
            <div class = "room-details">
              <span class = "room-name">・<%= room.name %></span>
              <div class = "room-comment">
                <p>
                  <% if room.comment.present? %>
                    <%= safe_join(room.comment.split("\n"), tag(:br)) %>
                  <% else %>
                    コメントなし
                  <% end %>
                </p>
              </div>
              <div class = "room-users">
                <span class = "room-users-h">参加ユーザー</span>
                <div>
                  <% room.users.each do |user| %>
                    <span>・<%= user.name %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <span id = "no-rooms">該当するルームが存在しません</span>
    <% end %>
  </div>
</div>

app/views/meeting_rooms/new.html.erb
<% if user_signed_in? %>
  <div id = "common-container">
    <div id = "new-room-container" style = "height: 100%; max-height: 1000px; width: 100%;">
      <div id = "rooms-menu" style = "height: 50px;">
        <%= link_to "ルーム一覧", meeting_rooms_path, id: "rooms-link" %>
        <%= link_to "過去ルーム一覧", meeting_rooms_past_index_path, id: "past-rooms-link" %>
        <span id = "new-room-link" style = "border-bottom: 5px solid #2196f3;">新規作成</span>
      </div>
      <div id = "meeting-lobby">
        <div id = meeting-new-form>
          <%= form_with model: @meeting_room, local: true do |f| %>
            <div id = "room-form" class = "meeting-new-form-sub">
              <div class = "form-container">
                <div class = "form-field" style = "height: 15%;">
                  <div class = "form-inner" id = "name-form">
                    <%= f.label :name, "ミーティング内容", class: "label" %>
                    <%= f.text_field :name, class: "form", placeholder: "15文字以内" %>
                  </div>
                </div>

                <div class = "form-field" style = "height: 25%;">
                  <div class = "form-inner" id = "comment-form">
                    <%= f.label :commnet, "コメント", class: "label" %>
                    <%= f.text_area :comment, class: "textarea", placeholder: "400字以内" %>
                  </div>
                </div>
                        
                <div class = "form-field" style = "height: 18%;">
                  <div class = "form-inner" id = "date-form">
                    <%= f.label :meeting_date, "日付", class: "label" %>
                    <%= f.date_field :meeting_date, class: "form", value: Date.today %>
                  </div>
                </div>
            
                <div class = "meeting-time-form form-field" style = "height: 17%;">
                  <div class = "form-inner" id = "start_form">
                    <%= f.label :start_at, "開始時間", class: "label" %>
                    <%= f.time_select :start_at, {minute_step: 10} %>
                  </div>
                </div>

                <div class = "meeting-time-form form-field" style = "height: 19%;">
                  <div class = "form-inner" id = "finish_form">
                    <%= f.label :finish_at, "終了時間", class: "label" %>
                    <%= f.time_select :finish_at, {minute_step: 10} %>
                  </div>
                </div>

                <div>
                  <%= f.submit "ルーム作成", class: "submit" %>
                </div>
              </div>
            </div>
            <div id = "entry-form" class = "meeting-new-form-sub">
              <div id = "non-select-user-list">
                <h6>ユーザーリスト</h6>
                <div id = "entry-users-select">
                  <% group_container_number = 0 %>
                  <% @departments.each do |department| %>
                    <div id = "entry-select-group-<%= group_container_number %>" class = "entry-select-group">
                      <span style = "pointer-events: none"><%= department.name %></span>
                      <input type="checkbox" class = "entry-group-check">
                    </div>
                    <ul id = "entry-select-list-<%= group_container_number %>" class = "entry-select-list">
                      <% department.users.each do |user| %>
                        <% if user != current_user %>
                          <li class = "entry-select-user-content">
                            <%= user.name %>
                            <input type="checkbox" class = "user_ids_<%= user.public_uid %>" value = "<%= user.public_uid %>">
                          </li>
                        <% end %>
                      <% end %>
                    </ul>
                    <% group_container_number += 1 %>
                  <% end %>
                  <% @contact_groups.each do |group| %>
                    <div id = "entry-select-group-<%= group_container_number %>" class = "entry-select-group">
                      <span style = "pointer-events: none"><%= group.name %></span>
                      <input type="checkbox" class = "entry-group-check">
                    </div>
                    <ul id = "entry-select-list-<%= group_container_number %>" class = "entry-select-list">
                      <% group.contact_group_relations.each do |relation| %>
                        <li class = "entry-select-user-content">
                          <%= relation.user.name %>
                          <input type="checkbox" class = "user_ids_<%= relation.user.public_uid %>" value = "<%= relation.user.public_uid %>">
                        </li>
                      <% end %>
                    </ul>
                    <% group_container_number += 1 %>
                  <% end %>
                </div>
              </div>
              <div id = "select-user-list">
                <h6>入室許可ユーザー</h6>
                <div id = "entry-selected-user-forms">
                    
                </div>
                <ul id = "selected-users">
                  <% if @meeting_room.errors.messages[:room_entry_users].present? %>
                    <span class = "entries-error">
                      <i class="fas fa-exclamation-circle"></i>
                      参加するユーザーを<br>選択してください
                    </span>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/meeting_rooms/past_index.html.erb
<div id = "common-container">
  <div id = "rooms-menu">
    <%= link_to "ルーム一覧", meeting_rooms_path, id: "rooms-link" %>
    <span id = "past-rooms-link" style = "border-bottom: 5px solid #2196f3;">過去ルーム一覧</span>
    <%= link_to "新規作成", new_meeting_room_path, id: "new-room-link" %>
    <div id = "menu-search-box">
      <%= form_with url: meeting_rooms_past_index_path, local: true, method: :get do |f| %>
        <%= f.label :name, "内容検索" %>
        <%= f.text_field :name %>

        <%= f.label :date, "日付検索" %>
        <%= f.date_field :date %>

        <%= f.submit "検索", id: "button" %>
      <% end %>
    </div>
  </div>
  <div id = "rooms-container">
    <% if @past_rooms.present? %>
      <ul>
        <% room_date = "foo" %>
        <% @past_rooms.each do |room| %>
          <% if room_date != room.start_at.strftime("%m月%d日") %>
            <% room_date = room.start_at.strftime("%m月%d日") %>
            <li class = "room-date-head"><%= room_date %></li>
          <% end %>
          <li class = "room-content">
            <span class = "room-status" style = "background: red;">終了</span>
            <span class = "room-time"><%= room.start_at.strftime("%m月%d日") %> <%= "#{room.start_at.strftime("%H:%M")}~#{room.finish_at.strftime("%H:%M")}" %></span>
            <%= link_to "ルームへ", meeting_room_path(room.public_uid), data: {"turbolinks"=>false}, class: "room-link" %>
            <%= link_to "ルーム削除", meeting_room_path(room.public_uid), class: "room-delete-link", method: :delete, data: { confirm: "ルーム名: #{room.name}を削除しますか？" } %>
            <div class = "room-details">
              <span class = "room-name">・<%= room.name %></span>
              <div class = "room-comment">
                <p>
                  <% if room.comment.present? %>
                    <%= safe_join(room.comment.split("\n"), tag(:br)) %>
                  <% else %>
                    コメントなし
                  <% end %>
                </p>
              </div>
              <div class = "room-users">
                <span class = "room-users-h">参加ユーザー</span>
                <div>
                  <% room.users.each do |user| %>
                    <span>・<%= user.name %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <span id = "no-rooms">該当するルームが存在しません</span>
    <% end %>
  </div>
</div>