config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    get "users/:id/edit" => "users/registrations#edit", as: :edit_other_user_registration
    match "users/:id", to: "users/registrations#update", via: [:patch, :put], as: :other_user_registration
    delete "users/:id/destroy", to: "users/registrations#destroy", as: :destroy_other_user_registration
  end

  # schedulesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_groupsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_group_relationsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # general_messagesに関するrouteはメッセージ読み込みアクションを除いて、JSフォーマット以外受け付けない(例外)
  # entriesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # room_messagesに関するrouteは全てJSフォーマット以外受け付けない(例外)

  root "homes#home"

  get "attendances" => "attendances#index"
  get "attendances/search" => "attendances#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "attendances/csv_download" => "attendances#csv_download", constraints: lambda { |req| req.format == :csv }

  get "user/modal_search" => "users#modal_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/search" => "users#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/sidebar_search" => "users#sidebar_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "users/modal_show/:id" => "users#modal_show", as: "user_modal_show", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "general_messages/other_user_chat_ajax" => "general_messages#message_ajax", constraints: lambda { |req| req.xhr? }
  get "general_messages/home_chat_ajax" => "general_messages#home_message_ajax", constraints: lambda { |req| req.xhr? }

  get "schedules/meeting_new" => "schedules#meeting_new", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/add_timer" => "schedules#add_timer", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/date_change" => "schedules#date_change", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "meeting_rooms/join/:id" => "meeting_rooms#join", as: "meeting_rooms_join", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "meeting_rooms/past_index" => "meeting_rooms#past_index"

  post "general_messages/multiple_create" => "general_messages#multiple_create", constraints: lambda { |req| req.xhr? && req.format == :js }

  resources :attendances, only: [:create, :update], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_group_relations, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_groups, only: [:create, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :departments, only: [:new, :create, :edit, :update, :destroy]
  resources :entries, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :general_messages, only: [:show, :create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :schedules, only: [:new, :create, :edit, :update, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :meeting_rooms, only: [:new, :create, :show, :index, :destroy]
  resources :room_messages, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :users, only: [:show, :index]
  resources :paid_holidays, only: [:create, :new]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # devise設定
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  # public_uid
  generate_public_uid

  def to_params
    public_uid
  end

  generate_public_uid generator: PublicUid::Generators::HexStringSecureRandom.new(16)

  # Userモデル　バリデーション
  validates :name, presence: true, length: { maximum: 10 }
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  validate :password_validate
  validates :department_id, presence: true
  validates :kana, presence: true, length: { maximum: 25 }

  # Userモデル 作成時パスワードバリデーション
  def password_validate
    if password.present?
      matched = password.match(VALID_PASSWORD_REGEX)
      unless matched
        errors.add(:password, "半角英数字のみ有効です")
      end
    end
  end

  # Schedule関連アソシエーション
  has_many :schedules, dependent: :delete_all

  # ContactGroup関連アソシエーション
  has_many :contact_groups, dependent: :delete_all
  has_many :contact_group_relations, dependent: :delete_all
  has_many :belong_to_groups, through: :contact_group_relations, source: :contact_group

  # GeneralMessage関連アソシエーション
  has_many :general_messages, dependent: :delete_all
  has_many :general_message_relations, dependent: :delete_all
  has_many :receive_messages, through: :general_message_relations, source: :general_message

  # MeetingRoom関連アソシエーション
  has_many :entries, dependent: :delete_all
  has_many :meeting_rooms, through: :entries
  has_many :room_messages, dependent: :delete_all

  # Attendance関連アソシエーション
  has_many :attendances, dependent: :delete_all

  # PaidHoliday関連アソシエーション
  has_many :paid_holidays, dependent: :delete_all

  # Department関連アソシエーション
  belongs_to :department

  def update_with_admin_password(params, admin_user)
    current_password = params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = if admin_user.valid_admin_user_password?(current_password)
        update(params)
      else
        assign_attributes(params)
        valid?
        errors.add(:current_password, current_password.blank? ? :blank : :invalid)
        false
      end
    clean_up_passwords
    result
  end

  def valid_admin_user_password?(password)
    Devise::Encryptor.compare(self.class, encrypted_password, password)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  prepend_before_action :require_no_authentication, :only => [:cancel]
  prepend_before_action :authenticate_scope!, :only => [:destroy, :new, :create, :edit, :update]

  # 管理ユーザー以外はルートへリダイレクト
  before_action :current_user_admin?, only: [:new, :create, :edit, :update, :destroy]

  # 勤怠情報取得
  before_action :get_sidebar_attendance, only: [:new, :edit]

  # GET /resource/sign_up
  def new
    @departments = Department.where.not(name: "未設定")
    @department_select = []
    @departments.each do |department|
      @department_select << [department.name, department.id]
    end
    build_resource
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    @departments = Department.where.not(name: "未設定")
    @department_select = []
    @departments.each do |department|
      @department_select << [department.name, department.id]
    end
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      set_flash_message! :notice, :signed_up
      redirect_to users_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      render :new
    end
  end

  # GET /resource/edit
  def edit
    @user = User.find_by(public_uid: params[:id])
    if @user.present?
      self.resource = resource_class.to_adapter.get!(@user.id)
      @departments = Department.where.not(name: "未設定")
      @department_select = []
      @departments.each do |department|
        @department_select << [department.name, department.id]
      end
    else
      redirect_to root_path
    end
  end

  # PUT /resource
  def update
    @user = User.find_by(public_uid: params[:id])
    self.resource = resource_class.to_adapter.get!(@user.id)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    resource_updated = update_resource(resource, account_update_params)
    
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in(current_user) if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      @departments = Department.where.not(name: "未設定")
      @department_select = []
      @departments.each do |department|
        @department_select << [department.name, department.id]
      end
      clean_up_passwords resource
      set_minimum_password_length
      render :edit
    end
  end

  # DELETE /resource
  def destroy
    @user = User.find_by(public_uid: params[:id])
    if @user
      if destroy_admin_password_valid?(params[:current_password])
        @user.destroy
        if current_user == @user
          Devise.sign_out_all_scopes ? sign_out : sign_out(current_user)
          redirect_to new_user_session_path
        else
          redirect_to users_path
        end
      else
        @departments = Department.where.not(name: "未設定")
        @department_select = []
        @departments.each do |department|
          @department_select << [department.name, department.id]
        end
        flash.now[:alert] = "管理者パスワードが不正です"
        render :edit
      end
    else
      redirect_to root_path
    end
  end


  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def update_resource(resource, params)
      resource.update_with_admin_password(params, current_user)
    end

    def after_update_path_for(resource)
      user_path(@user.public_uid)
    end

    def destroy_admin_password_valid?(password)
      current_user.valid_admin_user_password?(password)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_modal_search.html.erb
<div id = "user-search-response">
  <div id = "user-search-response-top-bar" class = "modal-top-bar">
    <ul>
      <li id = "user-search-response-back-btn" class = "topbar-back-btn"><span>⬅︎</span></li>
      <li id = "user-search-response-header" class = "topbar-header">ユーザー検索結果</li>
      <li id = "user-search-response-close" class = "topbar-close-btn"><span>＋</span></li>
    </ul>
  </div>
  <ul id = "search-user-list">
    <% if @search_users.present? %>
      <% @search_users.each do |user| %>
        <% unless current_user == user %>
          <%= link_to user_modal_show_path(user.public_uid), remote: true do %>
            <li><%= user.name %></li>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <div id = "not-user-list">
        <i class="fas fa-search"></i>
        <span>該当するユーザーが<br>存在しません</span>
      </div>
    <% end %>
  </ul>
</div>

app/views/users/_modal_show.html.erb
<div id = "user-content" data-user_id = "<%= @other_user.public_uid %>">
  <div id="user-content-top-bar" class = "modal-top-bar">
    <ul>
      <li id="user-content-back-btn" class = "topbar-back-btn"><span>⬅︎</span></li>
      <li id="user-content-header" class = "topbar-header">ユーザー詳細</li>
      <li id="user-content-close" class = "topbar-close-btn"><span>＋</span></li>
    </ul>
  </div>
  <div id = "user-left-content">
    <div id = "user-left-header">
      <h6>
        <% if @paid_holiday.present? %>
          <span class = "holiday status">有給休暇</span>
        <% elsif @status.present? %>
          <% if @status.left_at.present? %>
            <span class = "after-work status">退勤済</span>
          <% else %>
            <span class = "working status">勤務中</span>
          <% end %>
        <% else %>
          <span class = "before-work status">出勤前</span>
        <% end %>
        <%= @other_user.name %>
        <span class = "department">所属：<%= @other_user.department.name %></span>
      </h6>
      <button id = "add-group-btn">グループ追加</button>
    </div>
    <div id = "chat-log" data-other_page_count = "<%= @other_user_chat_page_count %>">
      <%= render "general_messages/other_user_chat" %>
    </div>
    <%= form_with(model: @new_message) do |f| %>
      <%= f.hidden_field :receive_user_id, value: @other_user.public_uid %>
      <%= f.text_area :content, id: "user-content-chat-text-area" %>
      <%= f.submit "送信", id: "chat-send-btn" %>
    <% end %>
  </div>
  <div id = "user-right-content">
    <div class = data-form>
      <%= form_with url: schedules_date_change_path, method: :get do |f| %>
        <%= f.hidden_field :user_id, value: @other_user.public_uid %>
        <%= f.date_field :browsing_user_schedule_date, class: "other-user-schedule-data-text", value: Date.today %>
        <%= f.submit "移動", class: "schedule-date-btn" %>
      <% end %>
    </div>
    <div class = "other-user-schedule-content" id = "other-user-schedule-content">
      <%= render "schedules/other_user_schedule" %>
    </div>
  </div>
</div>

<%= render "contact_group_relations/new" %>

app/views/users/_users_table.html.erb
<table class = "table" id = "myTable">
  <thead>
    <tr>
      <th onclick = "w3.sortHTML('#myTable','.item','td:nth-child(1)')">所属 <i class="fas fa-sort"></i></th>
      <th onclick = "w3.sortHTML('#myTable','.item','td:nth-child(2)')">ユーザー名 <i class="fas fa-sort"></i></th>
      <th onclick = "w3.sortHTML('#myTable','.item','td:nth-child(3)')">カタカナ <i class="fas fa-sort"></i></th>
      <th>アドレス</th>
      <th onclick = "w3.sortHTML('#myTable','.item','td:nth-child(5)')">権限 <i class="fas fa-sort"></i></th>
      <th>リンク</th>
      <th>編集</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class = "item">
        <td class = "department"><%= user.department.name %></td>
        <td><%= user.name %></td>
        <td><%= user.kana %></td>
        <td><%= user.email %></td>
        <% if user.admin? %>
          <td class = "edit">管理</td>
        <% else %>
          <td class = "edit">一般</td>
        <% end %>
        <td class = "edit"><%= link_to "詳細", user_path(user.public_uid) %></td>
        <td class = "edit"><%= link_to "編集", edit_other_user_registration_path(user.public_uid) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div id = "common-container">
  <div id = "management-top">
    <div id = "management-container">
      <div id = "management-user-container">  
        <div id = "users-table-container">
          <h2><i class="fas fa-list-alt"></i> ユーザーリスト</h2>
          <div id = "user-search">
            <%= form_with url: user_search_path, method: :get do |f| %>
              <div class = "form-field">
                <%= f.text_field :name, placeholder: "ユーザー名" %>
              </div>
              <div class = "form-field">
                <%= f.select :department, @department_select_option, { include_blank: "部署選択" } %>
              </div>
              <%= f.submit "検索", class: "btn" %>
            <% end %>
          </div>
          <%= render "users_table" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/modal_search.js.erb
<% #ユーザー検索ボックス（検索時）用JS %>
<% #ユーザー検索ボックス　非表示 %>
var user_search_box = document.getElementById("user-search-box");
user_search_box.style.display = "none";
<% #ユーザー検索結果 表示 %>
modal.insertAdjacentHTML("beforeend", "<%= j(render "users/modal_search") %>");
var user_search_response_container = document.getElementById("user-search-response");
user_search_response_container.style.display = "block";
var user_search_response_back_btn = document.getElementById("user-search-response-back-btn");
var user_search_response_close_btn = document.getElementById("user-search-response-close");
user_search_response_back_btn.onclick = () => {
  user_search_response_container.remove();
  user_search_box.style.display = "block";
}
user_search_response_close_btn.onclick = () => {
  modal.style.display = "none";
  user_search_response_container.remove();
}

app/views/users/modal_show.js.erb
<% if @other_user.present? && @other_user != current_user %>
  <% #ユーザー検索ボックス経由 %>
  var user_search_response_container = document.getElementById("user-search-response");
  if(user_search_response_container){
    <% #ユーザー検索結果 非表示 %>
    user_search_response_container.style.display = "none";
    <% #ユーザーページ 表示 %>
    modal.insertAdjacentHTML("beforeend", "<%= j(render "users/modal_show") %>");
    var other_user_content = document.getElementById("user-content");
    other_user_content.style.display = "block";
    var other_user_content_back_btn = document.getElementById("user-content-back-btn");
    var other_user_content_close_btn = document.getElementById("user-content-close");
    other_user_content_back_btn.onclick = () => {
      var add_user_to_group = document.getElementById("add-user-to-group");
      add_user_to_group.remove();
      other_user_content.remove();
      user_search_response_container.style.display = "block";
    }
    other_user_content_close_btn.onclick = () => {
      var add_user_to_group = document.getElementById("add-user-to-group");
      add_user_to_group.remove();
      other_user_content.remove();
      user_search_response_container.remove();
      modal.style.display = "none";
    }
  } else {
    <% #ユーザーサイドコンテナ経由 %>
    <% #ユーザーページ 表示 %>
    modal.style.display = "block";
    modal.insertAdjacentHTML("beforeend", "<%= j(render "users/modal_show") %>");
    var other_user_content = document.getElementById("user-content");
    other_user_content.style.display = "block";
    var other_user_content_back_btn = document.getElementById("user-content-back-btn");
    var other_user_content_close_btn = document.getElementById("user-content-close");
    other_user_content_back_btn.remove();
    other_user_content_close_btn.onclick = () => {
      var add_user_to_group = document.getElementById("add-user-to-group");
      add_user_to_group.remove();
      other_user_content.remove();
      modal.style.display = "none";
    }
  }
  <% #ユーザーページ　スケジュールBOX関連 %>
  var number = Number("<%= @other_user_schedules.length %>");
  for(var i=0; i < number; i++){
    var schedule = document.getElementsByClassName(`user-content-schedule-box-${i}`);
    var schedule_height = 0;
    for(var s=0; s < schedule.length; s++){
      if(i%2 == 0){
        schedule[s].style.backgroundColor = "rgba(29, 29, 29, 0.9)";
      } else {
        schedule[s].style.backgroundColor = "rgba(37, 76, 109, 0.9)";
      }
      schedule_height += schedule[s].offsetHeight;
    }
    if(schedule_height < 40){
      var schedule_time = document.getElementById(`other-user-schedule-time-${i}`);
      var schedule_name = document.getElementById(`other-user-schedule-name-${i}`);
      schedule_time.style.display = "none"
      schedule_name.style.display = "none";
      for(var s=0; s < schedule.length; s++){
        schedule[s].classList.add("other-need-details");
        if(s === 0){
          var schedule_details_element = document.createElement("p");
          schedule_details_element.setAttribute("id", `other-schedule-details-${i}`);
          schedule_details_element.setAttribute("class", `other-schedule-details`);
          var schedule_details_text_1 = document.createTextNode(`${schedule_name.textContent}`);
          var schedule_details_text_2 = document.createElement("br");
          var schedule_details_text_3 = document.createTextNode(`${schedule_time.textContent}`);
          schedule_details_element.appendChild(schedule_details_text_1);
          schedule_details_element.appendChild(schedule_details_text_2);
          schedule_details_element.appendChild(schedule_details_text_3);
          schedule[0].appendChild(schedule_details_element);
        }
        schedule[s].addEventListener("mouseover", (event) => {
          var schedule_number = (event.target.classList[0].replace(/[^0-9]/g, ''));
          var schedule_details = document.getElementById(`other-schedule-details-${schedule_number}`);
          schedule_details.style.display = "block";
        }, false);
        schedule[s].addEventListener("mouseleave", (event) => {
          var schedule_number = (event.target.classList[0].replace(/[^0-9]/g, ''));
          var schedule_details = document.getElementById(`other-schedule-details-${schedule_number}`);
          schedule_details.style.display = "none";
        }, false);
      }
    }
  }
  <% #ユーザーページ チャットログ関連 %>
  var other_user_chat_log = document.getElementById("chat-log");
  other_user_chat_log.scrollTo(0, other_user_chat_log.scrollHeight);
  var other_user_chat_page = 2;
  var other_user_chat_total_page = $("#chat-log").data("other_page_count");
  var other_user_chat_log = document.getElementById("chat-log");
  var other_user_chat_scroll_height = other_user_chat_log.scrollHeight;
  var other_user_chat_offset_height = other_user_chat_log.offsetHeight;
  if(other_user_chat_offset_height == other_user_chat_scroll_height && other_user_chat_total_page > 1){
    var other_user_chat_ajax_date = other_user_chat_log.getElementsByClassName("message-date")[0].id;
    var other_user_chat_content_scroll = other_user_chat_log.scrollHeight;
    $.ajax({
      url: `/general_messages/other_user_chat_ajax?page=${other_user_chat_page}&other_user=<%= @other_user.public_uid %>&message_date=${other_user_chat_ajax_date}`
    }).done(function(data) {
      $("#chat-log").scrollTop(other_user_chat_log.scrollHeight - other_user_chat_content_scroll);
      other_user_chat_page++;
    });
  }
  $("#chat-log").scroll(function(){
    if(($("#chat-log").scrollTop() == 0) && (other_user_chat_page <= Number(other_user_chat_total_page))){
      var other_user_chat_ajax_date = other_user_chat_log.getElementsByClassName("message-date")[0].id;
      var other_user_chat_content_scroll = other_user_chat_log.scrollHeight;
      $.ajax({
        url: `/general_messages/other_user_chat_ajax?page=${other_user_chat_page}&other_user=<%= @other_user.public_uid %>&message_date=${other_user_chat_ajax_date}`
      }).done(function(data) {
        $("#chat-log").scrollTop(other_user_chat_log.scrollHeight - other_user_chat_content_scroll);
        other_user_chat_page++;
      });
    }
  });
  <% # コンタクトグループ追加フォーム関連 %>
  var add_user_to_group = document.getElementById("add-user-to-group");
  var add_user_group_btn = document.getElementById("add-group-btn");
  add_user_group_btn.onclick = () => {
    other_user_content.style.display = "none";
    add_user_to_group.style.display = "block";
  }
  var add_user_to_group_back_btn = document.getElementById("add-user-to-group-back-btn");
  var add_user_to_group_close_btn = document.getElementById("add-user-to-group-close");
  add_user_to_group_back_btn.onclick = () => {
    add_user_to_group.style.display = "none";
    other_user_content.style.display = "block";
  }
  add_user_to_group_close_btn.onclick = () => {
    add_user_to_group.remove();
    other_user_content.remove();
    var user_search_response_container = document.getElementById("user-search-response");
    if(user_search_response_container){
      user_search_response_container.remove();
    }
    modal.style.display = "none"
  }
<% end %>

app/views/users/search.js.erb
var users_table = document.getElementById("users-table-container");
var table = users_table.getElementsByClassName("table")[0]
table.remove();
users_table.insertAdjacentHTML("beforeend", "<%= j(render "users_table") %>");

app/views/users/sidebar_search.js.erb
<% if @group.present? || @department.present? %>
  var group_search_section = document.getElementById("group-search-list");
  group_search_section.style.display = "none";
  var user_search_list_section = document.getElementById("group-search-section");
  user_search_list_section.insertAdjacentHTML("beforeend", "<%= j(render "homes/user_search_section") %>");

  var clock_container = document.getElementsByClassName("clock-container")[0];
  var clock_height = clock_container.clientHeight;

  var user_search_section = document.getElementById("user-search-list");
  var user_search_section_back_btn = document.getElementById("user-search-section-back-btn");
  var contact_group_delete_btn = document.getElementById("group-delete-link");

  user_search_section.style.height =  `calc(100% - ${clock_height}px)`; 

  user_search_section_back_btn.onclick = () => {
    user_search_section_back_btn.remove();
    user_search_section.remove();
    if(contact_group_delete_btn){
      contact_group_delete_btn.remove();
    }
    group_search_section.style.display = "block";
  }
<% end %>