config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    get "users/:id/edit" => "users/registrations#edit", as: :edit_other_user_registration
    match "users/:id", to: "users/registrations#update", via: [:patch, :put], as: :other_user_registration
    delete "users/:id/destroy", to: "users/registrations#destroy", as: :destroy_other_user_registration
  end

  # schedulesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_groupsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_group_relationsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # general_messagesに関するrouteはメッセージ読み込みアクションを除いて、JSフォーマット以外受け付けない(例外)
  # entriesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # room_messagesに関するrouteは全てJSフォーマット以外受け付けない(例外)

  root "homes#home"

  get "attendances" => "attendances#index"
  get "attendances/search" => "attendances#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "attendances/csv_download" => "attendances#csv_download", constraints: lambda { |req| req.format == :csv }

  get "user/modal_search" => "users#modal_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/search" => "users#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/sidebar_search" => "users#sidebar_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "users/modal_show/:id" => "users#modal_show", as: "user_modal_show", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "general_messages/other_user_chat_ajax" => "general_messages#message_ajax", constraints: lambda { |req| req.xhr? }
  get "general_messages/home_chat_ajax" => "general_messages#home_message_ajax", constraints: lambda { |req| req.xhr? }

  get "schedules/meeting_new" => "schedules#meeting_new", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/add_timer" => "schedules#add_timer", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/date_change" => "schedules#date_change", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "meeting_rooms/join/:id" => "meeting_rooms#join", as: "meeting_rooms_join", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "meeting_rooms/past_index" => "meeting_rooms#past_index"

  post "general_messages/multiple_create" => "general_messages#multiple_create", constraints: lambda { |req| req.xhr? && req.format == :js }

  resources :attendances, only: [:create, :update], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_group_relations, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_groups, only: [:create, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :departments, only: [:new, :create, :edit, :update, :destroy]
  resources :entries, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :general_messages, only: [:show, :create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :schedules, only: [:new, :create, :edit, :update, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :meeting_rooms, only: [:new, :create, :show, :index, :destroy]
  resources :room_messages, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :users, only: [:show, :index]
  resources :paid_holidays, only: [:create, :new]
end

app/views/shared/_header.html.erb
<header>
  <span id = "logo">Minaty</span>
  <% if user_signed_in? %>
    <button id = "sidebar-btn-trigger">
      <span></span>
      <span></span>
      <span></span>
    </button>
    <% if @timer_on.present? %>
      <div id = "header-time-btn">
        <i class="fas fa-stopwatch"></i> <span id = "btn-time">Timer</span>
      </div>
    <% end %>
  <% end %>
</header>

app/views/shared/_modal_message.html.erb
<div id = "modal-message">
  <h6><span id = "modal-message-delete">×</span></h6>
</div>

app/views/shared/_side_menu.html.erb
<nav>
  <ul id = "main-menu" class = "side-list"> 
    <li id = "current-user-content">
      <span class = "user-name"><i class="fas fa-id-card" style = "font-size: 18px;"></i><%= current_user.name %></span>
      <div id = "attendance-content">
        <%= render "shared/side_menu_attendance" %>
      </div>
      <%= link_to "ダッシュボード", user_path(current_user.public_uid), data: {"turbolinks"=>false}, class: "my-report-link" %>
      <%= link_to "有給休暇申請", new_paid_holiday_path, class: "my-report-link" %>
    </li>

    <%= link_to root_path, data: {"turbolinks"=>false} do %>
      <li>
        <span><i class="fas fa-home"></i>ホーム</span>
      </li>
    <% end %>
    <%= link_to meeting_rooms_path, data: {"turbolinks"=>false} do %>
      <li>     
        <span><i class="fas fa-headset"></i>ミーティング</span>
      </li>
    <% end %>
    <% if current_user.admin? %>
      <%= link_to users_path, data: {"turbolinks"=>false} do %>
        <li>
          <span><i class="fas fa-chalkboard-teacher"></i>ユーザー管理</span>
        </li>
      <% end %>

      <%= link_to new_user_registration_path, data: {"turbolinks"=>false} do %>
        <li>
          <span><i class="fas fa-user-plus"></i>ユーザー新規作成</span>
        </li>
      <% end %>

      <%= link_to attendances_path, data: {"turbolinks"=>false} do %>
        <li>
          <span><i class="fas fa-user-clock"></i>勤怠管理</span>
        </li>
      <% end %>

      <%= link_to new_department_path, data: {"turbolinks"=>false} do %>
        <li>
          <span><i class="fas fa-building"></i>部署設定</span>
        </li>
      <% end %>
    <% end %>

    <%= link_to destroy_user_session_path, method: :delete do %>
      <li>
        <span><i class="fas fa-sign-out-alt"></i>ログアウト</span>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_side_menu_attendance.html.erb
<% if @paid_holiday.present? %>
  <span class = "holiday">有給休暇中</span>
<% else %>
  <% if @sidebar_attendance.present? %>
    <% if @sidebar_attendance.left_at.present? %>
      <span class = "arrive">出勤時間： <%= @sidebar_attendance.arrived_at.strftime("%H時%M分") %></span>
      <span class = "leave">退勤時間： <%= @sidebar_attendance.left_at.strftime("%H時%M分") %></span>
    <% elsif @sidebar_attendance.arrived_at.present? %>
      <span class = "arrive">出勤時間： <%= @sidebar_attendance.arrived_at.strftime("%H時%M分") %></span>
      <%= link_to "退勤", attendance_path(@sidebar_attendance.id), method: :patch, remote: true, class: "leave", data: {confirm: "退勤時刻を打刻します"} %>
    <% end %>
  <% else %>
    <%= link_to "出勤", attendances_path, method: :post, remote: true, class: "arrive", data: {confirm: "出勤時刻を打刻します"} %>
  <% end %>
<% end %>

app/views/shared/_timer.html.erb
<div id = "timer-content">
  <div id = "timer-menu">
    <div id = "timer-start">
      start <i class="far fa-play-circle"></i>
    </div>
    <div id = "timer-stop">
      stop <i class="far fa-stop-circle"></i>
    </div>
    <div id = "timer-reset">
      reset <i class="fas fa-sync-alt"></i>
    </div>
  </div>
  <div id = "timer">
    00：00：00
  </div>
</div>
<div id = "timer-start-time-content">
  <%= link_to schedules_add_timer_path(start_time: "", end_time: ""), id: "timer-schedule-link" ,remote: true do %>
    <span id = "timer-add-schedule"><i class="fas fa-calendar-alt"></i> Add</span>
  <% end %>
  <span id = "timer-start-time">TIME</span>
</div>