config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => {
                       :registrations => "users/registrations",
                       :sessions => "users/sessions",
                     }

  devise_scope :user do
    get "users/:id/edit" => "users/registrations#edit", as: :edit_other_user_registration
    match "users/:id", to: "users/registrations#update", via: [:patch, :put], as: :other_user_registration
    delete "users/:id/destroy", to: "users/registrations#destroy", as: :destroy_other_user_registration
  end

  # schedulesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_groupsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # contact_group_relationsに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # general_messagesに関するrouteはメッセージ読み込みアクションを除いて、JSフォーマット以外受け付けない(例外)
  # entriesに関するrouteは全てJSフォーマット以外受け付けない(例外)
  # room_messagesに関するrouteは全てJSフォーマット以外受け付けない(例外)

  root "homes#home"

  get "attendances" => "attendances#index"
  get "attendances/search" => "attendances#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "attendances/csv_download" => "attendances#csv_download", constraints: lambda { |req| req.format == :csv }

  get "user/modal_search" => "users#modal_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/search" => "users#search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "user/sidebar_search" => "users#sidebar_search", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "users/modal_show/:id" => "users#modal_show", as: "user_modal_show", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "general_messages/other_user_chat_ajax" => "general_messages#message_ajax", constraints: lambda { |req| req.xhr? }
  get "general_messages/home_chat_ajax" => "general_messages#home_message_ajax", constraints: lambda { |req| req.xhr? }

  get "schedules/meeting_new" => "schedules#meeting_new", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/add_timer" => "schedules#add_timer", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "schedules/date_change" => "schedules#date_change", constraints: lambda { |req| req.xhr? && req.format == :js }

  get "meeting_rooms/join/:id" => "meeting_rooms#join", as: "meeting_rooms_join", constraints: lambda { |req| req.xhr? && req.format == :js }
  get "meeting_rooms/past_index" => "meeting_rooms#past_index"

  post "general_messages/multiple_create" => "general_messages#multiple_create", constraints: lambda { |req| req.xhr? && req.format == :js }

  resources :attendances, only: [:create, :update], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_group_relations, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :contact_groups, only: [:create, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :departments, only: [:new, :create, :edit, :update, :destroy]
  resources :entries, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :general_messages, only: [:show, :create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :schedules, only: [:new, :create, :edit, :update, :destroy], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :meeting_rooms, only: [:new, :create, :show, :index, :destroy]
  resources :room_messages, only: [:create], constraints: lambda { |req| req.xhr? && req.format == :js }
  resources :users, only: [:show, :index]
  resources :paid_holidays, only: [:create, :new]
end

app/models/general_message.rb
class GeneralMessage < ApplicationRecord

  # GeneralMessageモデル　バリデーション
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 400 }

  # User関連アソシエーション
  belongs_to :user

  # GeneralMessageRelation関連アソシエーション
  has_many :general_message_relations, dependent: :delete_all
  has_many :receive_users, through: :general_message_relations, source: :user
end

app/controllers/general_messages_controller.rb
class GeneralMessagesController < ApplicationController

  # ログインユーザー以外のアクセス拒否
  before_action :authenticate_user!

  # ルートパス以外からのアクセス拒否
  before_action :root_path_limits, only: [:show, :create, :message_ajax, :home_message_ajax]

  # ルートパス＆自分の持つミーティングルーム以外からのアクセス拒否
  before_action :validation_root_and_meeting, only: [:multiple_create]

  def show # format :js && ajax only
    # メッセージ取得
    general_message = current_user.general_messages.find_by(id: params[:id])
    if general_message
      # メッセージの送信先ユーザー取得
      @receive_users = general_message.receive_users
    end
  end

  def create # format :js && ajax only
    # 送信先ユーザー取得
    send_user = User.find_by(
      public_uid: params[:general_message][:receive_user_id],
    )
    if send_user && send_user != current_user
      # メッセージ作成
      @general_message = current_user.general_messages.build(
        general_message_params
      )
      if @general_message.save
        begin
          # 送信先に追加
          @general_message.receive_users << send_user
          # 送信先取得
          @receive_users = @general_message.receive_users
        rescue
          @general_message.destroy
        end
      end
    end
  end

  def multiple_create # format :js && ajax only
    # 送信先ユーザー取得(current_user以外)
    send_users = User.where(
      public_uid: params[:general_message_send_users],
    ).where.not(
      public_uid: current_user.public_uid,
    )
    if send_users.present?
      # メッセージ作成
      @general_message = current_user.general_messages.build(
        general_message_params
      )
      if @general_message.save
        begin
          # メッセージ送信先追加
          @general_message.receive_users << send_users
          @receive_users = @general_message.receive_users
        rescue
          @general_message.destroy
        end
      end
    end
    respond_to do |format|
      if root_url == request.referer
        format.js
      else
        format.js { render "general_messages/room_inside_create" }
      end
    end
  end

  # ユーザー詳細ページのチャットコンテンツの読み込み(スクロール時)
  def message_ajax # ajax only
    # 対象ユーザー取得
    @other_user = User.find_by(public_uid: params[:other_user])
    if @other_user && @other_user != current_user
      # 対象ユーザー宛のメッセージ取得
      current_messages = current_user.general_messages.includes(
        :general_message_relations
      ).where(
        general_message_relations: {
          user_id: @other_user.id,
        },
      )
      # 対象ユーザーからcurrent_userへのメッセージ取得
      other_messages = @other_user.general_messages.includes(
        :general_message_relations
      ).where(
        general_message_relations: {
          user_id: current_user.id,
        },
      )
      # 対象メッセージID取得
      @other_user_messages_ids = current_messages.ids + other_messages.ids
      # 対象メッセージ取得
      @other_user_messages = GeneralMessage.where(
        id: @other_user_messages_ids,
      ).includes(:user).order(created_at: "DESC").page(params[:page]).per(10).reverse
    end
    respond_to do |format|
      format.js
    end
  end

  # ホームチャットコンテンツの読み込み(スクロール時)
  def home_message_ajax # ajax only
    # 対象メッセージID取得
    @message_ids = current_user.general_message_ids + current_user.receive_message_ids
    # 対象メッセージ取得
    @messages = GeneralMessage.where(
      id: @message_ids,
    ).includes(
      :user, :receive_users
    ).order(created_at: "DESC").page(params[:page]).per(10).reverse
    respond_to do |format|
      format.js
    end
  end

  private

  # ストロングパラメータ
  def general_message_params
    params.require(:general_message).permit(:content)
  end
end

app/helpers/general_messages_helper.rb
module GeneralMessagesHelper
end

app/views/general_messages/_current_user_message.html.erb
<% # ホームメッセージコンテナ 送信時パーシャル %>
<div class = "message-content current-user">
  <span class = "message-user-name">
    送信先 :
    <%= link_to @receive_users.first.name, user_modal_show_path(@receive_users.first.public_uid), remote: true %>
    <% if @receive_users.length >= 2 %>
      <span>、他<%= @receive_users.length - 1 %>人</span>
    <% end %>
    <%= link_to "送信先一覧", general_message_path(@general_message.id), class: "send-users-display-btn", remote: true %>
  </span>
  <p class = "message">
    <%= safe_join(@general_message.content.split("\n"), tag(:br)) %>
    <% if @general_message.room_id.present? %>
      <br><%= link_to "スケジュール追加", schedules_meeting_new_path(meeting_room_id: @general_message.room_id), remote: true, class: "schedule-add-meeting" %>
      <br><%= link_to "ミーティングへ", meeting_room_path(@general_message.room_id) %>
    <% end %>
  </p>
  <span class = "message-time"><%= l @general_message.created_at %></span>
</div>

app/views/general_messages/_individual_current_message.html.erb
<% # ユーザー詳細メッセージ更新用　送信時パーシャル %>
<div class = "message-content current-user">
  <span class = "message-user-name">
    <%= @general_message.user.name %>
  </span>
  <p class = "message">
    <%= safe_join(@general_message.content.split("\n"), tag(:br)) %>
  </p>
  <span class = "message-time"><%= l @general_message.created_at %></span>
</div>

app/views/general_messages/_individual_other_message.html.erb
<% # ユーザー詳細メッセージ更新用　受信時パーシャル %>
<div class = "message-content other-user">
  <span class = "message-user-name">
    <%= message.user.name %>
  </span>
  <p class = "message">
    <%= safe_join(message.content.split("\n"), tag(:br)) %>
  </p>
  <span class = "message-time"><%= l message.created_at %></span>
</div>

app/views/general_messages/_other_user_message.html.erb
<% #　ホームメッセージコンテナ 受信時パーシャル %>
<div class = "message-content other-user" id = "general-message-<%= message.id %>">
  <span class = "message-user-name">
    <span class = "return-message-btn" data-message_user = "<%= message.user.public_uid %>"><i class="fas fa-share"></i> 返信 </span>
    <%= link_to message.user.name, user_modal_show_path(message.user.public_uid), remote: true %>
  </span>
  <p class = "message">
    <%= safe_join(message.content.split("\n"), tag(:br)) %>
    <% if message.room_id.present? %>
      <br><%= link_to "スケジュール追加", schedules_meeting_new_path(meeting_room_id: message.room_id), remote: true, class: "schedule-add-meeting" %>
      <br><%= link_to "ミーティングへ", meeting_room_path(message.room_id) %>
    <% end %>
  </p>
  <span class = "message-time"><%= l message.created_at %></span>
</div>

<script>
  var message_id = <%= message.id %>;
  var message_content = document.getElementById(`general-message-${message_id}`);
  var message_return_btn = message_content.getElementsByClassName("return-message-btn")[0];
  var setReturnMessage = (e) => {
    var user_name = e.target.nextElementSibling.textContent;
    var user_id = e.target.dataset.message_user;
    var chat_send_list_container = document.getElementById("send-list");
    var chat_send_user_list = document.getElementById("chat-send-user-list");
    var chat_send_form_list = document.getElementById("chat-send-users-form-list");
    var chat_send_form_input = chat_send_form_list.children;
    var check_selectors = chat_send_list_container.getElementsByClassName(`user-selector-${user_id}`);
    for(i=0; i < check_selectors.length;i++){
      var check_box = check_selectors[i].getElementsByTagName("input")[0];
      var user_list = check_selectors[i].parentNode;
      var user_list_selectors = user_list.children;
      var group_div = user_list.previousElementSibling;
      var group_div_checkbox = group_div.getElementsByTagName("input")[0];
      var selector_count = 0;
      check_box.checked = true;
      check_selectors[i].style.color = "black";
      check_selectors[i].style.backgroundColor = "white";
      for(var list_number=0; list_number < user_list_selectors.length;list_number++){
        if(user_list_selectors[list_number].getElementsByTagName("input")[0].checked){
          selector_count = selector_count +1;
        } 
        if(selector_count >= user_list_selectors.length){
          group_div_checkbox.checked = true;
        }
      }
    }

    for(i=0; i < chat_send_form_input.length;i++){
      var remove_user_id = chat_send_form_input[i].value;
      if(remove_user_id != user_id) {
        var remove_send_selector = chat_send_list_container.getElementsByClassName(`user-selector-${remove_user_id}`);
        for(s=0; s < remove_send_selector.length;s++){
          var remove_checkbox = remove_send_selector[s].getElementsByTagName("input")[0];
          remove_checkbox.checked = false;
          remove_send_selector[s].style.color = "white";
          remove_send_selector[s].style.backgroundColor = "";
          var user_list = remove_send_selector[s].parentNode;
          var user_list_selectors = user_list.children;
          var group_div = user_list.previousElementSibling;
          var group_div_checkbox = group_div.getElementsByTagName("input")[0];
          var selector_count = 0;
          for(var list_number=0; list_number < user_list_selectors.length;list_number++){
            if(user_list_selectors[list_number].getElementsByTagName("input")[0].checked){
              selector_count = selector_count -1;
            }
            if(selector_count <= 0){
              group_div_checkbox.checked = false;
            }
          }
        }
      } 
    }

    var send_user_element = document.createElement("li");
    var send_user_element_text = document.createTextNode(`${user_name}`);
    send_user_element.setAttribute("id", `send-selected-user-${user_id}`);
    send_user_element.setAttribute("class", "send-selected-users");
    send_user_element.appendChild(send_user_element_text);
    chat_send_user_list.innerHTML = "";
    chat_send_user_list.appendChild(send_user_element);
    var chat_send_form_element = document.createElement("input");
    chat_send_form_element.setAttribute("type", "hidden");
    chat_send_form_element.setAttribute("name", "general_message_send_users[]");
    chat_send_form_element.setAttribute("id", `chat-send-users-form-${user_id}`);
    chat_send_form_element.value = user_id;
    chat_send_form_list.innerHTML = "";
    chat_send_form_list.appendChild(chat_send_form_element);
  }
  message_return_btn.addEventListener("click", setReturnMessage);
</script>

app/views/general_messages/_show.html.erb
<div id = message-receivers-container>
  <div class = "modal-top-bar">
    <ul>
      <li class = "topbar-header">送信先一覧</li>
      <li id = "message-receivers-close" class = "topbar-close-btn"><span>＋</span></li>
    </ul>
  </div>
  <div id = "message-receivers-list">
    <ul>
      <% @receive_users.each do |user| %>
        <li class = "receiver-selector-<%= user.public_uid %> receiver-selector">
          <%= user.name %>
          <input type="checkbox" value = "<%= user.public_uid %>">
        </li>
      <% end %>
    </ul>
  </div>
  <button id = "receiver-list-all-select">一括選択</button>
</div>

app/views/general_messages/_side_message.html.erb
<% # サイドメッセージ受信用 %>
<div class = "message-content other">
  <span class = "message-name"><%= message.user.name %></span>
  <p></p>
  <span class = "message-date"><%= l message.created_at %></span>
</div>

app/views/general_messages/create.js.erb
var user_content_chat_area = document.getElementById("user-content-chat-text-area");

if(user_content_chat_area.value){
  user_content_chat_area.value = "";
}

<% if @receive_users.present? %>
  var chat_content = document.getElementById("chat-content");
  chat_content.insertAdjacentHTML("beforeend", "<%= j(render "general_messages/current_user_message") %>");
  chat_content.scrollTop = chat_content.scrollHeight;
  var chat_log = document.getElementById("chat-log");
  if(chat_log){
    chat_log.insertAdjacentHTML("beforeend", "<%= j(render "general_messages/individual_current_message") %>");
    chat_log.scrollTop = chat_log.scrollHeight;
  }
<% else %>
  alert("送信内容に不備があります。");
<% end %>

app/views/general_messages/home_message_ajax.html.erb
<%= render "homes/chat_container" %>

app/views/general_messages/home_message_ajax.js.erb
<% if @messages.present? %>
  var home_chat_log = document.getElementById("chat-content");
  <% if params[:message_date].present? && @messages.last.created_at.strftime("%m/%d") == params[:message_date] %>
    var message_date_head = home_chat_log.getElementsByClassName("message-date")[0];
    if(message_date_head){
      message_date_head.remove();
    }
  <% end %>
  home_chat_log.insertAdjacentHTML("afterbegin", "<%= j(render "homes/chat_container") %>");
  <% #返信ボタン %>
  var message_return_btn = document.getElementsByClassName("return-message-btn");
  var setReturnMessage = (e) => {
    var user_name = e.target.nextElementSibling.textContent;
    var user_id = e.target.dataset.message_user;
    var chat_send_list_container = document.getElementById("send-list");
    var chat_send_user_list = document.getElementById("chat-send-user-list");
    var chat_send_form_list = document.getElementById("chat-send-users-form-list");
    var chat_send_form_input = chat_send_form_list.children;
    var check_selectors = chat_send_list_container.getElementsByClassName(`user-selector-${user_id}`);
    for (i = 0; i < check_selectors.length; i++) {
      var check_box = check_selectors[i].getElementsByTagName("input")[0];
      var user_list = check_selectors[i].parentNode;
      var user_list_selectors = user_list.children;
      var group_div = user_list.previousElementSibling;
      var group_div_checkbox = group_div.getElementsByTagName("input")[0];
      var selector_count = 0;
      check_box.checked = true;
      check_selectors[i].style.color = "black";
      check_selectors[i].style.backgroundColor = "white";
      check_selectors[i].style.fontWeight = "bold";
      for (var list_number = 0; list_number < user_list_selectors.length; list_number++) {
        if (user_list_selectors[list_number].getElementsByTagName("input")[0].checked) {
          selector_count = selector_count + 1;
        }
        if (selector_count >= user_list_selectors.length) {
          group_div_checkbox.checked = true;
        }
      }
    }

    for (i = 0; i < chat_send_form_input.length; i++) {
      var remove_user_id = chat_send_form_input[i].value;
      if (remove_user_id != user_id) {
        var remove_send_selector = chat_send_list_container.getElementsByClassName(`user-selector-${remove_user_id}`);
        for (s = 0; s < remove_send_selector.length; s++) {
          var remove_checkbox = remove_send_selector[s].getElementsByTagName("input")[0];
          remove_checkbox.checked = false;
          remove_send_selector[s].style.color = "white";
          remove_send_selector[s].style.backgroundColor = "";
          remove_send_selector[s].style.fontWeight = "";
          var user_list = remove_send_selector[s].parentNode;
          var user_list_selectors = user_list.children;
          var group_div = user_list.previousElementSibling;
          var group_div_checkbox = group_div.getElementsByTagName("input")[0];
          var selector_count = 0;
          for (var list_number = 0; list_number < user_list_selectors.length; list_number++) {
            if (user_list_selectors[list_number].getElementsByTagName("input")[0].checked) {
              selector_count = selector_count - 1;
            }
            if (selector_count <= 0) {
              group_div_checkbox.checked = false;
            }
          }
        }
      }
    }

    var send_user_element = document.createElement("li");
    var send_user_element_text = document.createTextNode(`${user_name}`);
    send_user_element.setAttribute("id", `send-selected-user-${user_id}`);
    send_user_element.setAttribute("class", "send-selected-users");
    send_user_element.appendChild(send_user_element_text);
    chat_send_user_list.innerHTML = "";
    chat_send_user_list.appendChild(send_user_element);
    var chat_send_form_element = document.createElement("input");
    chat_send_form_element.setAttribute("type", "hidden");
    chat_send_form_element.setAttribute("name", "general_message_send_users[]");
    chat_send_form_element.setAttribute("id", `chat-send-users-form-${user_id}`);
    chat_send_form_element.value = user_id;
    chat_send_form_list.innerHTML = "";
    chat_send_form_list.appendChild(chat_send_form_element);
  }
  for (i = 0; i < message_return_btn.length; i++) {
    message_return_btn[i].addEventListener("click", setReturnMessage)
  }
<% end %>

app/views/general_messages/message_ajax.html.erb
<%= render "general_messages/other_user_chat" %>

app/views/general_messages/message_ajax.js.erb
<% if @other_user_messages.present? %>
  var modal_show_chat = document.getElementById("chat-log");
  <% if params[:message_date].present? && @other_user_messages.last.created_at.strftime("%m/%d") == params[:message_date] %>
    var message_date_head = modal_show_chat.getElementsByClassName("message-date")[0];
    if(message_date_head){
      message_date_head.remove();
    }
  <% end %>
  modal_show_chat.insertAdjacentHTML("afterbegin", "<%= j(render "general_messages/other_user_chat") %>");
<% end %>

app/views/general_messages/multiple_create.js.erb
var chat_send_users_list = document.getElementById("chat-send-user-list");
var chat_area = document.getElementById("chat-text-area");
if(chat_send_users_list.children.length != 0){
  if(chat_area.value){
    chat_area.value = "";
  }
}

<% if @receive_users.present? %>
  var chat_content = document.getElementById("chat-content");
  chat_content.insertAdjacentHTML("beforeend", "<%= j(render "general_messages/current_user_message") %>");
  chat_content.scrollTop = chat_content.scrollHeight;
<% else %>
  alert("送信先もしくは内容に不備があります。");
<% end %>

app/views/general_messages/room_inside_create.js.erb
<% if @receive_users.present? %>
  var room_message_container = document.getElementById("messages");
  room_message_container.insertAdjacentHTML("beforeend", "<%= j(render "room_messages/outside_current_add_room_message") %>");

  var room_message_side = document.getElementById("room-message-container");
  var outside_message_side = document.getElementById("outside-send-message-container");
  var room_message_side_btn = document.getElementById("room-message");
  var outside_message_side_btn = document.getElementById("outside-send-message-list");

  outside_message_side_btn.classList.remove("active");
  room_message_side_btn.classList.add("active");
  outside_message_side.style.display = "none";
  room_message_side.style.display = "inline-block";

  room_message_container.scrollTop = room_message_container.scrollHeight;

  var general_message_textarea = document.getElementById("general-message-textarea");
  if(general_message_textarea.value){
    general_message_textarea.value = "";
  }
<% else %>
  alert("メッセージの文字数か、送信先設定に不備があります。");
<% end %>